# Generated by Django 3.0.8 on 2020-08-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200725_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='flyer_img',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images'),
        ),
    ]
